name: whooie
version: 0.1.0
author: whooie
maintainer: wcwhuie@gmail.com
extra-source-files: []
synopsis: ''
description: ''
category: ''
dependencies:
  - base >= 4.7 && < 5
  - random >= 1.2
  - mtl >= 2.3.1
  - matplotlib >= 0.7.7
ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
library:
  source-dirs: lib
